### ISSUE TITLE
Highlight hard to distinguish

### ISSUE THREAD

**Issue by BruceLee569** [anzory/vscode-gppl-support#6]
Keyword functions and variables are highlighted in the same color, it's unlike your screenshot, so it's not easy to distinguish. Is this correct?
![image](https://github.com/anzory/vscode-gppl-support/assets/49506152/70c7a11f-4b26-4f47-ba9e-8559ab6783fe)

**Comment by anzory** [comment]
I couldn't replicate this issue. It is most likely not an extension problem. Please ensure that [Restricted Mode](https://code.visualstudio.com/docs/editor/workspace-trust), for example, is not enabled.

**Comment by anzory** [comment]
This issue occurred if a theme other than `Default Dark+` was chosen. It has been resolved in version 1.7.1, so please ensure you have updated.  Additionally, I suggest removing the `editor.tokenColourCustomisations` section entirely from your settings.json.
